# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ed5f6acd772551e7087f1b4cdf5688fa06a498e938990e38ef717ac84f5b1667fc598e89225c6eac5bd81d35801f6d55471c7330108c6f4b0bc2bb45c3900dd

test:
  secret_key_base: 823d6c9d748194d8eb8976a841f49ae5c739d7a0799e0f845bff497818bfe1f94e8b4a5c48843646375936606be61f565e8599d6c64f50180e1e9aad91c0adb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
